### ISSUE TITLE
Arduino receipe does not detect Version 2 

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/jps3-recipes#100]
Could you please update the recipes?

Thanks!

**Comment by jps3** [comment]
@workflowsguy: Thank you for bringing this to my attention, I had not seen any errors and never looked! I'll work on that this afternoon.

**Comment by jps3** [comment]
Fixed with d6814c2

**Comment by jps3** [comment]
Oops. Fixed the URL parsing. Didn't fix the change from ZIP to DMG … coming a.s.a.p.

**Comment by jps3** [comment]
And app name has changed from `Arduino.app` to `Arduino IDE.app`…

**Comment by jps3** [comment]
… and code signature …

**Comment by jps3** [comment]
Perhaps I should revert these changes and simply create new recipe(s) to handle the new IDE since I still see a “legacy” section on the download page whose regex matches the old one. Sorry for creating a bit of a mess rushing this everyone!

**Comment by jps3** [comment]
Reverted d6814c2

**Comment by jps3** [comment]
Should be resolved with #102
