### ISSUE TITLE
Brackets.munki Recipe, blocking_applications Needed?

### ISSUE THREAD

**Issue by foigus** [autopkg/jps3-recipes#14]
We're using your Brackets.munki recipe.

I noticed the following blocking_applications were added to the Brackets.munki recipe:
https://github.com/autopkg/jps3-recipes/blame/master/Adobe/Brackets.munki.recipe#L27-L31

The Munki wiki says (second bullet is the important part):
https://github.com/munki/munki/wiki/Blocking-Applications#details
> **Munki will skip any unattended_installs or unattended_uninstalls if:**
> 
> * There is a blocking_applications key in the pkginfo, and any application listed is running, or
> * *There is no blocking_applications key in the pkginfo, and any application in the installs list (if it exists) is running.*

I think blocking_applications of "Brackets" and "Brackets.app" aren't necessary since the recipe results in a copy_from_dmg Munki Installer Item, which includes Brackets in the "installs" array.  I'd fork and PR, but I'm not sure if you've had a different experience with the "automatic" blocking_applications coming from the "installs" array.

**Comment by jps3** [comment]
My apologies for the inexcusably long delay in replying, I had gotten a bit swamped with _crises du jour_ and projects. I will take a closer look at the Brackets recipes this afternoon. (Off hand I don't recall if I had a particular reason for doing it the way I did, or if that was the pattern I was following at the time...)
