### ISSUE TITLE
Pashua fail since change to https, 20cc4a0

### ISSUE THREAD

**Issue by seansgm** [autopkg/jps3-recipes#20]
If I run the new recipe with https, I get a fail:

`$ autopkg run -v Pashua.pkg.recipe
Processing Pashua.pkg.recipe...
URLDownloader
Couldn't download https://www.bluem.net/files/Pashua.dmg (HTTP Error 403: Forbidden)
Failed.
`

If I manually download it using curl it works fine:

`$ curl -O https://www.bluem.net/files/Pashua.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3592k  100 3592k    0     0  5145k      0 --:--:-- --:--:-- --:--:-- 5139k`

If I revert the download url to http, and run again using autopkg it also works:

`$ autopkg run -v Pashua.pkg.recipe
Processing Pashua.pkg.recipe...
URLDownloader
URLDownloader: Storing new Last-Modified header: Wed, 23 Dec 2015 08:21:58 GMT
URLDownloader: Downloaded /Volumes/DATA/autopkg/Cache/com.github.jps3.pkg.Pashua/downloads/Pashua.dmg
EndOfCheckPhase
...`

Running the latest version of autopkg:

`$ autopkg version
0.5.2
`

**Comment by jps3** [comment]
I could not replicate the error you were having with `https` vs `http`. Perhaps it was due to something temporary/transitory on their server? 

However, there was a lot of outdated cruft, and some bad recipe practice in there, since it was one of the first I had written. I have cleaned all the recipes up and will be pushing the changes shortly. All three recipes appear to be working properly, but please test and let me know.

**Comment by jps3** [comment]
Updates pushed to repo.

**Comment by seansgm** [comment]
Yeah, no change.  I can download the https url successfully through
multiple browsers or curl, I can download with autopkg using the original
http url, but autopkg still fails every time I run it with the https url
with a 403 error.

**Comment by jps3** [comment]
Very odd. I cannot replicate this problem at all. Did you update the recipes before running it again (stupid question, but it's very easy to forget to do).

Could you try running these commands and paste the results in a following comment in this thread?

```
$ autopkg repo-update https://github.com/autopkg/jps3-recipes.git
$ autopkg run -vv com.github.jps3.download.Pashua
```

_Example Output_
```
$ autopkg repo-update https://github.com/autopkg/jps3-recipes.git
ttempting git pull for /Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes...
Already up-to-date.

$ autopkg run -vv com.github.jps3.download.Pashua
Processing com.github.jps3.download.Pashua...
URLDownloader
{'Input': {'url': u'https://www.bluem.net/files/Pashua.dmg'}}
URLDownloader: Storing new Last-Modified header: Wed, 23 Dec 2015 08:21:58 GMT
URLDownloader: Downloaded /Users/user/Library/AutoPkg/Cache/com.github.jps3.download.Pashua/downloads/Pashua.dmg
{'Output': {'download_changed': True,
            'last_modified': 'Wed, 23 Dec 2015 08:21:58 GMT',
            'pathname': u'/Users/user/Library/AutoPkg/Cache/com.github.jps3.download.Pashua/downloads/Pashua.dmg',
            'url_downloader_summary_result': {'data': {'download_path': u'/Users/user/Library/AutoPkg/Cache/com.github.jps3.download.Pashua/downloads/Pashua.dmg'},
                                              'summary_text': 'The following new items were downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
Receipt written to /Users/user/Library/AutoPkg/Cache/com.github.jps3.download.Pashua/receipts/com.github.jps3.download-receipt-20160218-092420.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/user/Library/AutoPkg/Cache/com.github.jps3.download.Pashua/downloads/Pashua.dmg
```

As a sanity check, I get the following SHA1 hash for the Pashua.dmg downloaded on 2016-02-18 at 09:26 EST. The Pasua.app bundle within lists its `CFBundleVersion` as ` 0.10.3`.
```
$ shasum -a 1 ~/Library/AutoPkg/Cache/com.github.jps3.download.Pashua/downloads/Pashua.dmg
563dcc5443a7425def0ef0a23323a3aedf308485  /Users/user/Library/AutoPkg/Cache/com.github.jps3.download.Pashua/downloads/Pashua.dmg
```

**Comment by seansgm** [comment]
Yeah, updated.  I noticed you fixed the indentation, but for clarity:

$ autopkg repo-update https://github.com/autopkg/jps3-recipes

Attempting git pull for
/Volumes/DATA/autopkg/RecipeRepos/com.github.autopkg.jps3-recipes...

Already up-to-date.

$ autopkg run -vv com.github.jps3.download.Pashua

Processing com.github.jps3.download.Pashua...

URLDownloader

{'Input': {'url': u'https://www.bluem.net/files/Pashua.dmg'}}

Couldn't download https://www.bluem.net/files/Pashua.dmg (HTTP Error 403:
Forbidden)

Failed.

Receipt written to
/Volumes/DATA/autopkg/Cache/com.github.jps3.download.Pashua/receipts/com.github.jps3.download-receipt-20160218-202104.plist


The following recipes failed:

    com.github.jps3.download.Pashua

        Error in com.github.jps3.download.Pashua: Processor: URLDownloader:
Error: Couldn't download https://www.bluem.net/files/Pashua.dmg (HTTP Error
403: Forbidden)


Nothing downloaded, packaged or imported.


Obviously I can't shasum something I can't download, but if I run it
against the manually downloaded version I unsurprisingly get the same
result.


shasum -a 1 ~/Downloads/Pashua.dmg

563dcc5443a7425def0ef0a23323a3aedf308485
/Users/macadmin/Downloads/Pashua.dmg


What version of autopkg are you running?  Being able to download by any
other method would point the finger at the URLDownloader yet other
downloads are working fine, as is your download recipe for you!  And it
isn't a https thing either:


$ autopkg run -vv com.github.autopkg.download.googlechrome

Processing com.github.autopkg.download.googlechrome...

URLDownloader

{'Input': {'filename': u'GoogleChrome.dmg',

           'url': u'
https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg'}}

URLDownloader: Storing new Last-Modified header: Thu, 18 Feb 2016 03:25:00
GMT

URLDownloader: Storing new ETag header: "ac3f3"

URLDownloader: Downloaded
/Volumes/DATA/autopkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg

{'Output': {'download_changed': True,

            'etag': '"ac3f3"',

            'last_modified': 'Thu, 18 Feb 2016 03:25:00 GMT',

            'pathname':
u'/Volumes/DATA/autopkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg',

            'url_downloader_summary_result': {'data': {'download_path':
u'/Volumes/DATA/autopkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg'},

                                              'summary_text': 'The
following new items were downloaded:'}}}

EndOfCheckPhase

{'Input': {}}

{'Output': {}}

Receipt written to
/Volumes/DATA/autopkg/Cache/com.github.autopkg.download.googlechrome/receipts/com.github.autopkg.download-receipt-20160218-205840.plist


The following new items were downloaded:

    Download Path


    -------------



/Volumes/DATA/autopkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg



I'm going to tcpdump/wireshark to see if I can see anything else, but if
you could confirm the version of autopkg you are using and the OS that you
are running autopkg on I'd appreciate it.

**Comment by seansgm** [comment]
tcpdump didn't show anything to talk about.  Still a problem today.  Can
you confirm your versions?

**Comment by jps3** [comment]
_Quick Note:_
_It's difficult to read the output you're pasting in. When doing so, it's helpful to use the Markdown provisions available. Example, an inline command `ls -l /Users` is simply surrounded by a single backquote. A block of output/program text can be had using a triple-backquote alone on a line, followed by the text, followed by another triple-backquote on a following line._

_It would greatly assist legibility if you would please edit the last response or two in which you're including output._

I asked on the macadmins.slack.com #autopkg channel if anyone could give this recipe a quick test. Several replied that it was working for them as well. I am not sure what to suggest next, or what may be occurring. Could you try from another computer with a different IP address, perhaps?

As a sanity check I have tested the recipe from a Mac an another campus (different network) and that worked fine as well.

It seems like this must be something local to the computer you're running this on, or something about it (or it's network/connection) that's causing the www.bluem.net server to generate a `403` response. Perhaps capturing traffic for both autopkg and curl/wget and examining request and response headers might give some further clue.

I'm sorry, this must be frustrating! At the moment, I'm not sure what else to suggest...
