### ISSUE TITLE
Suspicious Package download seems to be failing

### ISSUE THREAD

**Issue by jessepeterson** [autopkg/jps3-recipes#23]
Looks like with v3 it changed to a xip download.

http://www.mothersruin.com/software/SuspiciousPackage/get.html

Download here:

http://www.mothersruin.com/software/downloads/SuspiciousPackage.xip

(old URL http://www.mothersruin.com/software/downloads/SuspiciousPackage.pkg is giving a 404)

**Comment by gregneagle** [comment]
See also https://github.com/autopkg/gregneagle-recipes/tree/master/SuspiciousPackageXip

**Comment by gregneagle** [comment]
And also: https://github.com/autopkg/eholtam-recipes/tree/master/SuspiciousPackageApp

**Comment by gregneagle** [comment]
(I'd recommend using eholtam's -- mine was an experiment to see if I could do anything useful with xip archives and it requires not-yet released versions of several Processors)

**Comment by jessepeterson** [comment]
Well, I just plain didn't put enough effort into looking for alternative recipes. My bad. :)
