### ISSUE TITLE
WacomIntuosProDriver.munki package fail

### ISSUE THREAD

**Issue by swy** [autopkg/jps3-recipes#27]
On run, WacomIntuosProDriver.munki fails on determining the LSMinimumSystemVersion by reading the Info.plist file.  This key is no longer present, replaced with this key:

`    <key>LSMinimumSystemVersionByArchitecture</key>
        <dict>
                <key>x86_64</key>
                <string>10.8</string>
        </dict>`

**Comment by gregneagle** [comment]
See https://github.com/autopkg/jps3-recipes/pull/26

No action by the author. :-(

**Comment by swy** [comment]
Oh.. there's already a PR submitted for this.  https://github.com/autopkg/jps3-recipes/pull/26

**Comment by swy** [comment]
What Greg said. :P

**Comment by gregneagle** [comment]
Let's keep it open -- hopefully the author will notice and react. How about it @jps3?

**Comment by jps3** [comment]
Sorry, I am not getting notices (again), for some reason. I will work on this asap. Apologies for the delay.

**Comment by gregneagle** [comment]
I've done the work, see https://github.com/autopkg/jps3-recipes/pull/26.  All you need to do is merge. :-)

**Comment by gregneagle** [comment]
BTW, pulling the minimum os version from the Distribution file is more accurate/useful than pulling it from one of  the installed apps. In my investigation I saw the minimum os version in some of the apps reported as "10.8", yet the package itself would refuse to install on anything older than 10.9...

**Comment by jps3** [comment]
Apologies to all for the delay!
