### ISSUE TITLE
Sketchup issue

### ISSUE THREAD

**Issue by stretch-monster** [autopkg/jps3-recipes#33]
Hi,

I'm not sure if I'm posting this in the correct area, but I seem to be having an issue.  A quick little background.  I have recently taken over the care and feeding of the Munki server, and I am trying to get up to speed on it.  Munki is sending out these errors:

$ autopkg run SketchUpPro.munki
Processing SketchUpPro.munki...
Error processing path '/private/tmp/dmg.mB0EdF/SketchUp 2016/LayOut.app' with glob. 
Failed.

The following recipes failed:
    SketchUpPro.munki
        Error in com.github.jps3.munki.SketchUpPro: Processor: CodeSignatureVerifier: Error: Error processing path '/private/tmp/dmg.mB0EdF/SketchUp 2016/LayOut.app' with glob. 

Nothing downloaded, packaged or imported.

I did run the updater to be sure:

misod:tmp admin$ autopkg repo-update all
Attempting git pull for /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.thenikola-recipes...
Already up-to-date.

Attempting git pull for /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes...
Already up-to-date.

Attempting git pull for /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes...
Already up-to-date.

Attempting git pull for /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes...
Already up-to-date.

I am using 
autopkg version
0.6.1
on 10.11.6

Thanks

**Comment by jps3** [comment]
Sorry for delay in replying! (I seem to have frequent issues with not receiving notifications from GitHub for this account, and I am not sure why.)

Are you still having this issue?

**Comment by joshua-d-miller** [comment]
I'm still receiving this issue with SketchUpPro as well 👍

**Comment by jps3** [comment]
Okay. Odd. I'm not getting that on my end. Could one of you post your AutoPkg override file? (Note it's helpful to wrap in the triple-backtick markdown for easier readability). I think it would also be helpful to see the output of `autopkg run -vvv local.munki.SketchUpPro` (or whatever the identifier is for the override on your system).

**Comment by joshua-d-miller** [comment]
I'm sorry, I needed to change my year and this was resolved. Thanks!

**Comment by jps3** [comment]
No worries! Maybe I should review this recipe and see if there isn't a neater/nicer/better way to do it.
