### ISSUE TITLE
Wacom Drivers Error

### ISSUE THREAD

**Issue by dwilkshh** [autopkg/jps3-recipes#40]
Hey,

The latest version of the Wacom drivers are causing issues in Munki because there's a hyphen in the version number. I changed the version number in the pkginfo (removed the hyphen) and then renamed the plist to contain the same version number - finally, I re-added it to my manifest and then it began working. Just thought I would give you a heads up.

Best,

D

**Comment by jps3** [comment]
Sorry I missed this. I seem to not always get (or notice?) Github notifications. Please feel free to 'bump' any issues you submit to anyone here if no reply in a reasonable amount of time.
