### ISSUE TITLE
WacomIntousProDriver.munki recipe needs blocking_applications array

### ISSUE THREAD

**Issue by gregneagle** [autopkg/jps3-recipes#45]
Since the recipe has a lengthy installs array and no blocking_applications array, Munki uses the applications in the installs array as a virtual blocking_applications array.

This means that the user is prompted to quit any of the following apps:
Wacom Desktop Center.app
Wacom Display Settings.app
Wacom Tablet Utility.app
WacomTabletDriver.app

The last one is problematic as it is a faceless background app that auto-relaunches: there's no reasonable way for a normal user to quit this.

I'd propose adding:

```xml
<key>blocking_applications</key>
<array>
    <string>Wacom Desktop Center.app</string>
    <string>Wacom Display Settings.app</string>
    <string>Wacom Tablet Utility.app</string>
</array>
```

to the pkginfo.

**Comment by jps3** [comment]
Any issues with the current state of these Wacom recipes (with respect to my updates per your suggestions)? Ok to close this issue?

**Comment by gregneagle** [comment]
The change seems correct to me. Go ahead and close.

**Comment by jps3** [comment]
Awesome. Cheers. And thank you for the suggestions, I needed that gentle shove. (I had let my Munki-fu lag!)
