### ISSUE TITLE
SketchUpPro.download.recipe is broken.

### ISSUE THREAD

**Issue by jps3** [autopkg/jps3-recipes#48]
The SketchUpPro.download.recipe is not working as intended. Setting the RELEASE_YEAR variable only effectively works (currently) if set to "2017." The current version ("2018") does not have the year in the download URL or filename, thus negating the intention of the recent changes to the recipe.

I will work out a more useful schema to handle this as soon as possible.

**Comment by macmule** [comment]
FWIW, I created a new recipe for 2018: https://github.com/autopkg/dataJAR-recipes/blob/master/SketchUp%20Pro%202018%20EN/SketchUp%20Pro%202018%20EN.download.recipe

Same URL, but hardcoded the year into the CodeSignatureVerifier paths. Which I hope will catch the years
