### ISSUE TITLE
SketchUp munki receipe

### ISSUE THREAD

**Issue by nilsbyte** [autopkg/jps3-recipes#54]
I am using AutoPkg with the com.github.jps3.munki.SketchUpPro receipe. I made a local override for the locale (DE) but AutoPkg downloads and logs it again on every run. Sometimes, there is a version number, sometimes not. But it's logged with 

```
*New software available for testing:*

- SketchUpPro-de: 18.0.16976
```

```
*The following new items were downloaded:*

/Users/admin/Library/AutoPkg/Cache/local.munki.SketchUpPro/downloads/SketchUpPro-de.dmg
```

I don't know why this happens. Every other software in my receipe list works without problems.

**Comment by jps3** [comment]
I am closing this as I had left it here to stagnate as I do not have a clean solution I am happy with. (Also our use of SketchUp Pro here has dropped in my areas of responsibility, so it is not such a focus or priority.)
