### ISSUE TITLE
Arduino.munki.recipe Hdiutil Error

### ISSUE THREAD

**Issue by dcoobs** [autopkg/jps3-recipes#57]
We're seeing the following error in the Arduino recipe:

```
The following recipes failed:
    Arduino.munki.recipe
        Error in local.munki.Arduino: Processor: DmgCreator: Error: creation of /Users/Shared/AutoPkg/Cache/local.munki.Arduino/arduino-1.8.6.dmg failed: hdiutil: create failed - No space left on device
```

A quick look at this makes me suspect that the issue stems from the **dmg_megabytes** variable being set to 500MB but the Arduino app itself is around 530MB.

**Comment by jps3** [comment]
I am seeing the same error here. Thank you for this error report, I had not noticed the error messages in my notifications.

I should have an opportunity to look at and correct this well before Monday.
