### ISSUE TITLE
Possible typo in Wacom uninstall_script

### ISSUE THREAD

**Issue by gregneagle** [autopkg/jps3-recipes#6]
https://github.com/autopkg/jps3-recipes/blob/master/WacomIntuosProDriver/WacomIntuosProDriver.munki.recipe#L42

Might "Wacom Table Utility" supposed to be "Wacom Tablet Utility"?

**Comment by jps3** [comment]
Not sure, I haven't kept up with their product offerings. Didn't Ikea buy them out? (Har har.)

I'll fix that right up. Thanks for pointing that out. I can't believe I missed that all this time!

**Comment by jps3** [comment]
Ah ha. And it looks like the script is failing because the perl script is assuming certain env vars to be present. (I thought they'd changed/fixed that at some point in the past...) I will work on this.

**Comment by jps3** [comment]
Fix pushed.
