### ISSUE TITLE
SketchUpPro download broken

### ISSUE THREAD

**Issue by joshua-d-miller** [autopkg/jps3-recipes#7]
Hello @jps3.  The download of SketchUpPro fails and says it cannot find a match on the site.

Thanks!

**Comment by jps3** [comment]
Thanks for the notice. I'll look into it now.

**Comment by jps3** [comment]
I'm not getting/seeing any errors in my testing. Are you using a recipe override of it by chance?

**Comment by joshua-d-miller** [comment]
I am using a recipe override however I'm getting this error:

        Error in local.munki.SketchUpPro: Processor: URLTextSearcher: Error: No match found on URL: http://www.sketchup.com/download/all

**Comment by joshua-d-miller** [comment]
So I found my issue.  I needed to take the space out of name for the URL search.  Sorry about that!  Thanks for checking with me!

**Comment by jps3** [comment]
No worries.
