### ISSUE TITLE
WacomIntuosProDriver munki import reciept version issue

### ISSUE THREAD

**Issue by poundbangbash** [autopkg/jps3-recipes#8]
I noticed today when running the recipe to update the software that Wacom doesn't version their .pkg correctly and it pulls the pkg receipt into munki as version 0.  This makes munki think the software is already installed and won't offer to install the latest version.

Could the recipe be edited to use MunkiInstallsItemsCreator so it will check installed bundle versions instead of receipt version?

It appears the application bundles below are all versioned with their name in the CFBundleShortVersionString. However the CFBundleVersion are consistent at `6.3.13f3` 
Using CFBundleVersion as the comparison would be consistent for all bundles that are installed that I can see.

Paths to the bundles that could be used in the installs array in the recipe:
  /Applications/Wacom Tablet.localized/Wacom Tablet Utility.app
  /Applications/Wacom Tablet.localized/Wacom Desktop Center.app
  /Library/Application Support/Tablet/WacomTabletDriver.app
  /Library/PreferencePanes/WacomTablet.prefpane

I started looking at the code to possibly do a PR but I've not created a recipe like that before.  I noticed you have a few recipes (Sketchup, TotalTerminal, SuspiciousPackageQLP) that do use the key so maybe you'd be more familiar with the syntax and process.

**Comment by jps3** [comment]
I had known of the issue from awhile back, and I thought it was working, but I will admit I have not checked it in quite awhile. Thank you for pointing that out. Best to get this fixed as I am rolling out some new labs and refreshes shortly that will need it.

**Comment by jps3** [comment]
I have made the changes, tested the updated munki recipe, tested import into a live Munki repo, and tested client. All appears so far to be working ok. The only thing I have not yet tested is plugging a Wacom tablet into that test client (dept that uses them does not leave them in my labs over summer).

Please give it a test run for yourself as well, and let me know.

**Comment by poundbangbash** [comment]
That was quick!  Thanks.  I'll take a look.

**Comment by poundbangbash** [comment]
Looks good.
I removed the existing pkg and pgkinfo for the latest version I already had in Autopkg and munki and re-imported via your updated recipe.  Running `managedsoftwareupdate -vv` on a client that I installed the latest driver version on earlier today shows the installed version satisfied the installs array. 

```
* Processing manifest item WacomIntuosProDriver for install
    Looking for detail for: WacomIntuosProDriver, version latest...
    Considering 1 items with name WacomIntuosProDriver from catalog testing-wacom-intuos
    Considering item WacomIntuosProDriver, version 6.3.13w3 with minimum os version required 10.8
    Our OS version is 10.10.3
    Found WacomIntuosProDriver, version 6.3.13w3 in catalog testing-wacom-intuos
    	Found Info.plist at /Applications/Wacom Tablet.localized/Wacom Tablet Utility.app/Contents/Info.plist
    	Checking /Applications/Wacom Tablet.localized/Wacom Tablet Utility.app/Contents/Info.plist for CFBundleVersion 6.3.13f3...
    	Using version_comparison_key CFBundleVersion
    	Installed item has version 6.3.13f3
    	Installed item is the same.
    	Found Info.plist at /Applications/Wacom Tablet.localized/Wacom Desktop Center.app/Contents/Info.plist
    	Checking /Applications/Wacom Tablet.localized/Wacom Desktop Center.app/Contents/Info.plist for CFBundleVersion 6.3.13f3...
    	Using version_comparison_key CFBundleVersion
    	Installed item has version 6.3.13f3
    	Installed item is the same.
    	Found Info.plist at /Library/Application Support/Tablet/WacomTabletDriver.app/Contents/Info.plist
    	Checking /Library/Application Support/Tablet/WacomTabletDriver.app/Contents/Info.plist for CFBundleVersion 6.3.13f3...
    	Using version_comparison_key CFBundleVersion
    	Installed item has version 6.3.13f3
    	Installed item is the same.
    	Found Info.plist at /Library/PreferencePanes/WacomTablet.prefpane/Contents/Info.plist
    	Checking /Library/PreferencePanes/WacomTablet.prefpane/Contents/Info.plist for CFBundleVersion 6.3.13f3...
    	Using version_comparison_key CFBundleVersion
    	Installed item has version 6.3.13f3
    	Installed item is the same.
    WacomIntuosProDriver version 6.3.13w3 (or newer) is already installed.
    Looking for updates for: WacomIntuosProDriver
    Looking for updates for: WacomIntuosProDriver-6.3.13w3
    Looking for updates for: WacomIntuosProDriver--6.3.13w3
```

**Comment by jps3** [comment]
Thanks for pointing the problem out. I don't get around to auditing my old recipes as often as I should. The nudge helps. :-)

**Comment by poundbangbash** [comment]
No problem. All for the greater good.

-Eric
